"""Feed parser for external blocklist feeds.

Handles parsing blocklist file content into validated IP sets
and formatting IP sets back into standard blocklist file format.
"""

from __future__ import annotations

import ipaddress
import logging
import time

import requests

from services.blocklist_service import BlocklistService
from services.feed_types import FeedFetchError, FeedParseResult


class FeedParser:
    """Parses and formats blocklist feed content."""

    HEADER = "# Generated by IP Active Response"

    logger = logging.getLogger(__name__)

    def __init__(self, blocklist_service: BlocklistService, timeout: int = 30):
        """Initialize with a BlocklistService for IP validation.

        Args:
            blocklist_service: Service instance used to validate IPs.
            timeout: HTTP request timeout in seconds (used by fetch_and_parse).
        """
        self.blocklist_service = blocklist_service
        self.timeout = timeout

    def fetch_and_parse(self, url: str) -> FeedParseResult:
        """Download blocklist from URL, parse and validate IPs.

        Returns FeedParseResult with ip_set, raw_line_count, valid_count, error.
        Raises FeedFetchError on HTTP failures (non-2xx, timeouts, connection errors).
        """
        headers = {
            "Cache-Control": "no-cache",
            "Pragma": "no-cache",
        }
        separator = "&" if "?" in url else "?"
        bust_url = f"{url}{separator}_cb={int(time.time())}"

        try:
            response = requests.get(bust_url, headers=headers, timeout=self.timeout)
            response.raise_for_status()
        except requests.exceptions.Timeout:
            self.logger.error("Timeout fetching feed from %s", url)
            raise FeedFetchError(
                f"Request timed out after {self.timeout}s fetching {url}"
            )
        except requests.exceptions.ConnectionError as exc:
            self.logger.error("Connection error fetching feed from %s: %s", url, exc)
            raise FeedFetchError(f"Connection error fetching {url}: {exc}")
        except requests.exceptions.HTTPError as exc:
            status_code = exc.response.status_code if exc.response is not None else None
            self.logger.error(
                "HTTP %s error fetching feed from %s", status_code, url
            )
            raise FeedFetchError(
                f"HTTP {status_code} error fetching {url}", status_code=status_code
            )
        except requests.exceptions.RequestException as exc:
            self.logger.error("Error fetching feed from %s: %s", url, exc)
            raise FeedFetchError(f"Error fetching {url}: {exc}")

        content = response.text
        raw_line_count = len(content.splitlines())
        ip_set = self.parse_content(content)

        return FeedParseResult(
            ip_set=ip_set,
            raw_line_count=raw_line_count,
            valid_count=len(ip_set),
        )

    def parse_content(self, content: str) -> set[str]:
        """Parse blocklist file content into a deduplicated set of valid IPs.

        - Skips lines starting with # or ;
        - Skips blank lines
        - Trims whitespace
        - Handles inline comments (# or ;)
        - Validates each IP via BlocklistService.validate_ip()
        - Returns normalized, deduplicated IP set
        """
        result: set[str] = set()

        for line in content.splitlines():
            line = line.strip()

            # Skip blank lines
            if not line:
                continue

            # Skip full-line comments
            if line.startswith("#") or line.startswith(";"):
                continue

            # Strip inline comments: take everything before the first # or ;
            for sep in ("#", ";"):
                idx = line.find(sep)
                if idx != -1:
                    line = line[:idx]

            line = line.strip()
            if not line:
                continue

            # Validate the IP
            is_valid, _ = self.blocklist_service.validate_ip(line)
            if is_valid:
                # Normalize to match BlocklistService storage format
                if "/" in line:
                    normalized = str(ipaddress.ip_network(line, strict=False))
                else:
                    addr = ipaddress.ip_address(line)
                    suffix = "/128" if isinstance(addr, ipaddress.IPv6Address) else "/32"
                    normalized = str(addr) + suffix
                result.add(normalized)

        return result

    def format_blocklist(self, ip_set: set[str]) -> str:
        """Serialize a set of IPs into standard blocklist file format.

        Output: '# Generated by SOC IP Blocker' header, followed by
        sorted IPs, one per line.
        """
        lines = [self.HEADER] + sorted(ip_set)
        return "\n".join(lines) + "\n"
