"""Feed parser for external blocklist feeds.

Handles parsing blocklist file content into validated IP sets
and formatting IP sets back into standard blocklist file format.
"""

from __future__ import annotations

import ipaddress
import json
import logging
import time

import requests

from services.blocklist_service import BlocklistService
from services.feed_types import FeedFetchError, FeedParseResult


class FeedParser:
    """Parses and formats blocklist feed content."""

    HEADER = "# Generated by IP Active Response"

    logger = logging.getLogger(__name__)

    def __init__(self, blocklist_service: BlocklistService, timeout: int = 30):
        """Initialize with a BlocklistService for IP validation.

        Args:
            blocklist_service: Service instance used to validate IPs.
            timeout: HTTP request timeout in seconds (used by fetch_and_parse).
        """
        self.blocklist_service = blocklist_service
        self.timeout = timeout

    def fetch_and_parse(self, url: str) -> FeedParseResult:
        """Download blocklist from URL, parse and validate IPs.

        Returns FeedParseResult with ip_set, raw_line_count, valid_count, error.
        Raises FeedFetchError on HTTP failures (non-2xx, timeouts, connection errors).
        """
        headers = {
            "Cache-Control": "no-cache",
            "Pragma": "no-cache",
        }
        separator = "&" if "?" in url else "?"
        bust_url = f"{url}{separator}_cb={int(time.time())}"

        try:
            response = requests.get(bust_url, headers=headers, timeout=self.timeout)
            response.raise_for_status()
        except requests.exceptions.Timeout:
            self.logger.error("Timeout fetching feed from %s", url)
            raise FeedFetchError(
                f"Request timed out after {self.timeout}s fetching {url}"
            )
        except requests.exceptions.ConnectionError as exc:
            self.logger.error("Connection error fetching feed from %s: %s", url, exc)
            raise FeedFetchError(f"Connection error fetching {url}: {exc}")
        except requests.exceptions.HTTPError as exc:
            status_code = exc.response.status_code if exc.response is not None else None
            self.logger.error(
                "HTTP %s error fetching feed from %s", status_code, url
            )
            raise FeedFetchError(
                f"HTTP {status_code} error fetching {url}", status_code=status_code
            )
        except requests.exceptions.RequestException as exc:
            self.logger.error("Error fetching feed from %s: %s", url, exc)
            raise FeedFetchError(f"Error fetching {url}: {exc}")

        content = response.text
        if not content or not content.strip():
            raise FeedFetchError(f"Empty response body from {url}")

        return self.parse_content(content)

    def parse_content(self, content: str) -> FeedParseResult:
        """Parse blocklist file content into a FeedParseResult.

        Dispatches to the appropriate parser based on content format.
        If the content is detected as NDJSON (first non-empty line is a JSON
        object with a "cidr" key), delegates to _parse_ndjson; otherwise
        delegates to _parse_text.

        Returns FeedParseResult with ip_set, raw_line_count, valid_count, invalid_count.
        """
        if self._detect_ndjson(content):
            return self._parse_ndjson(content)
        return self._parse_text(content)

    def _detect_ndjson(self, content: str) -> bool:
        """Detect whether content is in NDJSON format.

        Returns True if the first non-empty line is valid JSON containing a "cidr" key.
        """
        for line in content.splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                parsed = json.loads(line)
                return isinstance(parsed, dict) and "cidr" in parsed
            except (json.JSONDecodeError, ValueError):
                return False
        return False

    def _parse_ndjson(self, content: str) -> FeedParseResult:
        """Parse NDJSON content into a FeedParseResult.

        Each line is expected to be a JSON object with a "cidr" key.
        Lines with invalid JSON, missing "cidr" key, or invalid CIDR values
        are counted as invalid and skipped.

        Returns FeedParseResult with ip_set, raw_line_count, valid_count, invalid_count.
        """
        ip_set: set[str] = set()
        raw_line_count = len(content.splitlines())
        valid_count = 0
        invalid_count = 0

        for line in content.splitlines():
            line = line.strip()
            if not line:
                continue

            # Try to parse JSON
            try:
                obj = json.loads(line)
            except (json.JSONDecodeError, ValueError):
                invalid_count += 1
                continue

            # Extract "cidr" key
            if not isinstance(obj, dict) or "cidr" not in obj:
                invalid_count += 1
                continue

            cidr_value = obj["cidr"]

            # Validate and normalize as IP network
            try:
                network = ipaddress.ip_network(cidr_value, strict=False)
                normalized = str(network)
                ip_set.add(normalized)
                valid_count += 1
            except (ValueError, TypeError):
                invalid_count += 1
                continue

        return FeedParseResult(
            ip_set=ip_set,
            raw_line_count=raw_line_count,
            valid_count=valid_count,
            invalid_count=invalid_count,
        )


    def _parse_text(self, content: str) -> FeedParseResult:
        """Parse text blocklist content into a FeedParseResult with invalid line tracking.

        - Skips lines starting with # or ;
        - Skips blank lines
        - Trims whitespace
        - Handles inline comments (# or ;)
        - Validates each IP via BlocklistService.validate_ip()
        - Tracks invalid_count for non-comment, non-blank lines that fail validation
        - Returns FeedParseResult with ip_set, raw_line_count, valid_count, invalid_count
        """
        ip_set: set[str] = set()
        raw_line_count = len(content.splitlines())
        valid_count = 0
        invalid_count = 0

        for line in content.splitlines():
            line = line.strip()

            # Skip blank lines
            if not line:
                continue

            # Skip full-line comments
            if line.startswith("#") or line.startswith(";"):
                continue

            # Strip inline comments: take everything before the first # or ;
            for sep in ("#", ";"):
                idx = line.find(sep)
                if idx != -1:
                    line = line[:idx]

            line = line.strip()
            if not line:
                continue

            # Validate the IP
            is_valid, _ = self.blocklist_service.validate_ip(line)
            if is_valid:
                # Normalize to match BlocklistService storage format
                if "/" in line:
                    normalized = str(ipaddress.ip_network(line, strict=False))
                else:
                    addr = ipaddress.ip_address(line)
                    suffix = "/128" if isinstance(addr, ipaddress.IPv6Address) else "/32"
                    normalized = str(addr) + suffix
                ip_set.add(normalized)
                valid_count += 1
            else:
                invalid_count += 1

        return FeedParseResult(
            ip_set=ip_set,
            raw_line_count=raw_line_count,
            valid_count=valid_count,
            invalid_count=invalid_count,
        )


    def format_blocklist(self, ip_set: set[str]) -> str:
        """Serialize a set of IPs into standard blocklist file format.

        Output: '# Generated by SOC IP Blocker' header, followed by
        sorted IPs, one per line.
        """
        lines = [self.HEADER] + sorted(ip_set)
        return "\n".join(lines) + "\n"
